apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.15.0
    helm:
      values: |
        provider:
          name: aws
        env:
          - name: AWS_DEFAULT_REGION
            value: us-east-1
        sources:
          - ingress
          - service
        domainFilters:
          - hasankadado.com
        txtOwnerId: external-dns
        policy: sync
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::820242908024:role/eks-devops-platform-external-dns-role

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true